TeacherRoomsIndexViewの作成
18jn02-8/telledge pull request #101
Opened 2019-12-08 05:14 UTC by KAZUPRO

・TeacherRoomsIndexViewの作成(検証済み)
・未確定属性直接入力

2019-12-08 08:49 UTC, Tatsuki5274 requested changes

2019-12-08 08:49 UTC, Tatsuki5274 commented on telledge/Views/Teachers/Rooms/index.cshtml
>  <!DOCTYPE html>
マスタページに展開されるためdoctype宣言が二重になる。

2019-12-08 08:51 UTC, Tatsuki5274 requested changes

2019-12-08 08:51 UTC, Tatsuki5274 commented on telledge/Views/Teachers/Rooms/index.cshtml
> +									<td><h3>家</h3></td>
このデータ項目は仮データではなく実データを入力する

2019-12-08 08:51 UTC, Tatsuki5274 commented on telledge/Views/Teachers/Rooms/index.cshtml
> +									<td><h3>３０００ポイント</h3></td>
このデータ項目は仮データではなく実データを入力する

2019-12-08 08:52 UTC, Tatsuki5274 commented
未確定属性はないはず。

2019-12-08 10:05 UTC, KAZUPRO commented
・実データに修正済み（テスト済み）

2019-12-08 12:45 UTC, Tatsuki5274 requested changes

2019-12-08 12:45 UTC, Tatsuki5274 commented on telledge/Views/Teachers/Rooms/index.cshtml
>  <html>
htmlタグはマスタページに存在するため含めてはいけない。

2019-12-09 06:09 UTC, KAZUPRO commented on telledge/Views/Teachers/Rooms/index.cshtml
>  <html>
htmlタグ削除済み（テスト検証済み）

2019-12-09 07:37 UTC, Tatsuki5274 approved these changes

2019-12-09 07:37 UTC, merged