生徒のRoomsコントローラーのSearchビューの雛形作成
18jn02-8/telledge pull request #166
Opened 2019-12-23 07:04 UTC by KAZUPRO

・Serachビューファイルの作成
・簡易的なビューの作成

2019-12-23 13:11 UTC, Tatsuki5274 requested changes
怪しい変更を確認。
コントローラなしで動作を確認？
動作確認済み？

2019-12-23 13:11 UTC, Tatsuki5274 commented on telledge/telledge.csproj
> +        <XspParameters Port="8080" Address="127.0.0.1" SslMode="None" SslProtocol="Default" KeyType="None" CertFile="" KeyFile="" PasswordOptions="None" Password="" Verbose="True" />
これは一体何？？？

2019-12-23 13:11 UTC, Tatsuki5274 commented on telledge/Views/Students/Rooms/search.cshtml
> +@model telledge.Models.Room
これの使い道は？

2019-12-23 14:31 UTC, KAZUPRO commented on telledge/telledge.csproj
> +        <XspParameters Port="8080" Address="127.0.0.1" SslMode="None" SslProtocol="Default" KeyType="None" CertFile="" KeyFile="" PasswordOptions="None" Password="" Verbose="True" />
自動生成されて全く分かりません。。。。危険です

2019-12-23 14:31 UTC, KAZUPRO commented on telledge/Views/Students/Rooms/search.cshtml
> +@model telledge.Models.Room
現状ありません。

2019-12-23 14:37 UTC, KAZUPRO commented
Viewとコントローラーに依存関係があったのですが、分かりにくくなってしまうと思い、Viewとコントローラーを分けてプルリクエストしようと思いました。このViewはChrome HTML Document (.html)で画面レイアウトの形だけ作ったものです。説明不足ですいません。このプルリクはCloseしたほうがいいですか？

2019-12-24 02:19 UTC, closed without merging

2019-12-24 02:25 UTC, Tatsuki5274 commented on telledge/telledge.csproj
> +        <XspParameters Port="8080" Address="127.0.0.1" SslMode="None" SslProtocol="Default" KeyType="None" CertFile="" KeyFile="" PasswordOptions="None" Password="" Verbose="True" />
手動で削除してもいいかもしれない