生徒の検索画面の作成
18jn02-8/telledge pull request #170
Opened 2019-12-24 04:54 UTC by KAZUPRO

・生徒の検索画面の作成（動作確認済み）
・Searchコントローラー（Get、Post）の作成
・CSSファイルの作成
・CSSコードの作成

2019-12-24 05:11 UTC, Tatsuki5274 requested changes

2019-12-24 05:11 UTC, Tatsuki5274 commented on telledge/telledge.csproj
> +        <XspParameters Port="8080" Address="127.0.0.1" SslMode="None" SslProtocol="Default" KeyType="None" CertFile="" KeyFile="" PasswordOptions="None" Password="" Verbose="True" />
この設定は必要？

2019-12-24 07:21 UTC, Tatsuki5274 requested changes

2019-12-24 07:21 UTC, Tatsuki5274 commented on telledge/Views/Students/Rooms/search.cshtml
> +<html>
htmlタグが二重になってない？

2019-12-24 09:30 UTC, KAZUPRO commented on telledge/Views/Students/Rooms/search.cshtml
> +<html>
修正しました。

2019-12-24 09:32 UTC, KAZUPRO commented on telledge/telledge.csproj
> +        <XspParameters Port="8080" Address="127.0.0.1" SslMode="None" SslProtocol="Default" KeyType="None" CertFile="" KeyFile="" PasswordOptions="None" Password="" Verbose="True" />
この不明な自動生成を削除すると、アクセスが拒否されましたとエラーメッセージが表示され実行など含めて何もできなくなります。

2019-12-24 09:33 UTC, KAZUPRO commented on telledge/telledge.csproj
> +        <XspParameters Port="8080" Address="127.0.0.1" SslMode="None" SslProtocol="Default" KeyType="None" CertFile="" KeyFile="" PasswordOptions="None" Password="" Verbose="True" />
visualStdioをアップデートしたところ、この自動生成が生まれました。

2019-12-24 09:35 UTC, KAZUPRO commented on telledge/telledge.csproj
> +        <XspParameters Port="8080" Address="127.0.0.1" SslMode="None" SslProtocol="Default" KeyType="None" CertFile="" KeyFile="" PasswordOptions="None" Password="" Verbose="True" />
不必要なので消去しました

2019-12-25 00:07 UTC, Tatsuki5274 approved these changes

2019-12-25 00:07 UTC, merged