生徒の登録情報変更画面の作成
18jn02-8/telledge pull request #177
Opened 2019-12-26 07:09 UTC by KAZUPRO

・登録情報変更画面の作成（実行確認済み）
・Viewファイルの作成
・アクションの作成（edit、update）
・telledge/Views/Students/Rooms/index.cshtmlにedit画面への遷移追加

2019-12-26 08:33 UTC, Tatsuki5274 requested changes
情報を変更しない場合はデータを上書きしないようにする必要がありそう。
文字列長が０文字なら～～～

2019-12-26 08:33 UTC, Tatsuki5274 commented on telledge/Controllers/Students/HomesController.cs
> +			Student student = new Student();
Student student = Student.currentUser()の方がいいかも

2019-12-26 10:04 UTC, KAZUPRO commented on telledge/Controllers/Students/HomesController.cs
> +			Student student = new Student();
修正しておきます。

2019-12-26 11:44 UTC, KAZUPRO commented
指摘点修正しました。
・未入力の属性があると、""がDBに上書きされてしまっていたので修正
・Student student = Student.currentUser()　に修正（効率化）

2019-12-27 01:00 UTC, Tatsuki5274 requested changes

2019-12-27 01:00 UTC, Tatsuki5274 commented on telledge/Controllers/Students/HomesController.cs
> +			student.passwordDigest = student.passwordDigest;//ログイン済みパスワードダイジェスト取得
同じ値に代入してるけど無意味なのでは？

2019-12-27 03:47 UTC, KAZUPRO commented on telledge/Controllers/Students/HomesController.cs
> +			student.passwordDigest = student.passwordDigest;//ログイン済みパスワードダイジェスト取得
もし一つでも未入力の場合、未入力の属性には””文字がDBに上書きされてしまっていて、その対策として未入力の場合（””文字の場合）、ログイン済みであるStudent.currentUser()から元々DBに登録してある情報を代入しています。これにより、””文字の上書き問題は解消しました。

2019-12-27 03:50 UTC, KAZUPRO commented on telledge/Controllers/Students/HomesController.cs
> +			student.passwordDigest = student.passwordDigest;//ログイン済みパスワードダイジェスト取得
気づきませんでした。ご指摘ありがとうございます。

2019-12-27 04:08 UTC, Tatsuki5274 requested changes

2019-12-27 04:08 UTC, Tatsuki5274 commented on telledge/Controllers/Students/HomesController.cs
> +				mailaddress = student.mailaddress;
このmailaddressオブジェクトの意味は？
何故代入している？

2019-12-27 04:08 UTC, Tatsuki5274 commented on telledge/Controllers/Students/HomesController.cs
> +			student.mailaddress = mailaddress;
mailadressが空データとして入力された場合はチェックせずに空データを上書きするってこと？

2019-12-27 04:14 UTC, Tatsuki5274 requested changes
student.mailaddressに対象データ入れずにデータの更新できる？？？

2019-12-27 04:58 UTC, KAZUPRO commented
指摘点を修正しました。

2019-12-27 05:35 UTC, Tatsuki5274 approved these changes

2019-12-27 05:35 UTC, merged