生徒のパスワード変更画面の作成
18jn02-8/telledge pull request #180
Opened 2019-12-28 04:27 UTC by KAZUPRO

・パスワード変更画面の作成
・テスト実行済み（入力されなかった場合、空文字が入った場合、新しいパスワードと確認用パスワードが異なった場合、現在のパスワード（ハッシュ化）とDBにあるパスワードダイジェストが異なった場合）
・Viewファイルの作成
・editアクション（Get）の作成
・Updateアクション（Post）の作成

2019-12-28 04:34 UTC, Tatsuki5274 requested changes
同じ処理を何度も記述するのはナンセンス。
changePasswordメソッドを利用するべき。

2019-12-28 04:35 UTC, KAZUPRO commented
changePasswordメソッドではPasswordDigestに代入しているため、比較できない。

2019-12-28 04:41 UTC, KAZUPRO commented
changePasswordメソッドがあったなんて！！使います。

2019-12-28 04:45 UTC, Tatsuki5274 commented
それでコードがシンプルになるはず

2019-12-28 04:55 UTC, Tatsuki5274 requested changes

2019-12-28 04:55 UTC, Tatsuki5274 commented on telledge/Controllers/Students/PasswordsController.cs
> +					student.setPassword(createPassword);
changePasswordで変更した後にもう一回変更する必要はなくない？

2019-12-28 05:00 UTC, KAZUPRO commented on telledge/Controllers/Students/PasswordsController.cs
> +					student.setPassword(createPassword);
確認しました。ごもっともです。変更します。

2019-12-28 05:15 UTC, KAZUPRO commented on telledge/Controllers/Students/PasswordsController.cs
> +					student.setPassword(createPassword);
student.setPasswordに値をセットしないと、変更後ログインできないことが分かりました。

2019-12-28 05:32 UTC, KAZUPRO commented on telledge/Controllers/Students/PasswordsController.cs
> +					student.setPassword(createPassword);
ChangePasswordメソッド自体に不備があると思います。確認よろしくお願い致します。

2020-01-04 11:50 UTC, Tatsuki5274 requested changes

2020-01-04 11:50 UTC, Tatsuki5274 commented on telledge/Controllers/Students/PasswordsController.cs
> +			if(createPassword == ConfirmationPassword)
比較する前に更新してるため、パスワードがcreatePasswordとConfirmationPasswordが異なっていたらchangePasswordの処理が無駄になる可能性がある。
ロジックの改修がしにくいため見やすいコードが好ましい。

2020-01-04 11:50 UTC, Tatsuki5274 commented on telledge/Controllers/Students/PasswordsController.cs
> +		public ActionResult update(String oldPassword,String createPassword,String ConfirmationPassword)
このメソッドはどのリクエストで実行される？
フォームの指定が見当たらない・・・

2020-01-04 12:42 UTC, KAZUPRO commented on telledge/Controllers/Students/PasswordsController.cs
> +			if(createPassword == ConfirmationPassword)
なるほど。。ごもっともです
更新しちゃうね。順番間違えてました。

2020-01-04 12:47 UTC, KAZUPRO commented on telledge/Controllers/Students/PasswordsController.cs
> +		public ActionResult update(String oldPassword,String createPassword,String ConfirmationPassword)
telledge/Views/Students/Passwords/edit.cshtml で入力した情報をformタグで送っています。

2020-01-04 23:11 UTC, Tatsuki5274 requested changes

2020-01-04 23:11 UTC, Tatsuki5274 commented on telledge/Views/Students/Rooms/index.cshtml
> +		<a href="/student/Passwords/edit">パスワード変更画面</a>
formで何も送らないならformである必要はなくない？

2020-01-05 03:25 UTC, KAZUPRO commented on telledge/Views/Students/Rooms/index.cshtml
> +		<a href="/student/Passwords/edit">パスワード変更画面</a>
アンカータグだけの遷移に修正しました。Formタグの認識とアンカータグの認識を間違えてました。

2020-01-05 04:10 UTC, Tatsuki5274 approved these changes

2020-01-05 04:10 UTC, merged