callコントローラーとCreateコントローラーの作成
18jn02-8/telledge pull request #74
Opened 2019-11-28 07:35 UTC by KAZUPRO

・callコントローラーの作成
・Createコントローラーの作成

2019-11-28 12:51 UTC, Tatsuki5274 requested changes
callコントローラとcreateコントローラを記述する設計はないはず。

2019-11-28 13:06 UTC, Tatsuki5274 requested changes
全体的にpull requestの変更説明と変更内容が相違している

2019-11-29 00:49 UTC, KAZUPRO commented
> ・callコントローラーの作成
> ・Createコントローラーの作成
・Teacherのログインメソッドの細かな修正
・

2019-11-29 00:51 UTC, KAZUPRO commented
> ・callコントローラーの作成
> ・Createコントローラーの作成
・HTML骨組みをVisualSudioのViewsファイルに貼り付け

2019-12-01 03:01 UTC, closed without merging