ModalWindow雛形作成
18jn02-8/telledge pull request #87
Opened 2019-12-05 01:48 UTC by KAZUPRO

・ModalWindow雛形作成

2019-12-05 01:50 UTC, Tatsuki5274 requested changes

2019-12-05 01:50 UTC, Tatsuki5274 commented on telledge/Views/Teachers/Rooms/call.cshtml
> +	<script src="https://cdn.jsdelivr.net/npm/jquery@3/dist/jquery.min.js"></script>
CDNは使わないほうがいい。

2019-12-05 01:50 UTC, Tatsuki5274 commented on telledge/Views/Teachers/Rooms/call.cshtml
> +	<script src="http://localhost:53766/Scripts/jquery-3.3.1.js"></script>
LocalhostのファイルをCDNで読み込んでいる。

2019-12-05 02:58 UTC, KAZUPRO commented on telledge/Views/Teachers/Rooms/call.cshtml
> +	<script src="https://cdn.jsdelivr.net/npm/jquery@3/dist/jquery.min.js"></script>
CDN削除

2019-12-05 02:59 UTC, KAZUPRO commented on telledge/Views/Teachers/Rooms/call.cshtml
> +	<script src="http://localhost:53766/Scripts/jquery-3.3.1.js"></script>
ＣＤＮでの読み込み取り消し

2019-12-05 04:24 UTC, Tatsuki5274 requested changes

2019-12-05 04:24 UTC, Tatsuki5274 commented on telledge/Views/Teachers/Rooms/call.cshtml
> +		$(function () {
JavaScriptコードの再利用性を高めるためにjsファイルに移動させる必要がある。

2019-12-05 04:24 UTC, Tatsuki5274 commented on telledge/Views/Teachers/Rooms/call.cshtml
> +				<input class="buttom-margin" type="submit" value="対応不可" id="button-color-red">
確かsubmitはformタグ内で利用する属性。
発火はjsでするためtype属性は不要。

2019-12-05 04:24 UTC, Tatsuki5274 commented on telledge/Views/Teachers/Rooms/call.cshtml
> +	<script src="main.js"></script>
main.jsは何の目的のファイル？

2019-12-05 04:24 UTC, Tatsuki5274 commented on telledge/Views/Teachers/Rooms/call.cshtml
> +				return false;
謎の戻り値false。
使い道は？

2019-12-07 04:31 UTC, Tatsuki5274 requested changes

2019-12-07 04:31 UTC, Tatsuki5274 commented on telledge/Views/Teachers/Rooms/call.cshtml
> +		$(function () {
別の画面でもモーダルウィンドウを利用するため `JavaScript` と `CSS` を切り出すことが好ましい。

2019-12-07 08:03 UTC, closed without merging