Issue 2019/12/06
18jn02-8/telledge pull request #96
Opened 2019-12-06 06:30 UTC by KAZUPRO

・Indexアクションの多重定義解消
・RedirectToRutesに変更（講師ページから生徒ページに遷移してします問題解消）
・誤字修正

2019-12-07 04:27 UTC, Tatsuki5274 requested changes

2019-12-07 04:27 UTC, Tatsuki5274 commented on telledge/Controllers/Teachers/SessionsController.cs
> +            return View("create");
この指定でファイルを参照できる？

2019-12-07 04:51 UTC, KAZUPRO commented on telledge/Controllers/Teachers/SessionsController.cs
> +            return View("create");
参照できるように修正しました。

2019-12-08 02:57 UTC, Tatsuki5274 approved these changes

2019-12-08 02:57 UTC, merged